### ISSUE TITLE
MAJ du plugin suite au changement d'url.

### ISSUE THREAD

**Issue by CarlosRGL** [plaurent75/tipi#3]
Bonjour, c'est prévu une MAJ du plugin suite au changement de l'adresse pour le payement (https://www.tipi.budget.gouv.fr/ -> https://www.payfip.gouv.fr)

Merci

**Comment by plaurent75** [comment]
https://github.com/plaurent75/tipi/commit/b28da76db560ff9679eddf0c8b05200de02d8806
